#Basic Setting
title: Proto
email: test@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Proto工作室
baseurl: /Blog1 # the subpath of your site, e.g. /blog
url: "https://protobb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  protobb
excerpt_separator:  '<!-- more -->'

sass:
    sass_dir: _sass

# Build settings
markdown: kramdown
theme: minima

#Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

#Plugins settings
paginate: 3
feed:
  path: atom.xml
  excerpt_only: true

#Other vars
ga_id: UA-38227412-4
fb_id: 586617358361449
