title: Tars表示
email: janelin612@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  工程師不打誑語
baseurl: "https://janelin612.github.io/" # the subpath of your site, e.g. /blog
url: "https://janelin612.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  janelin612

# Build settings
markdown: kramdown
theme: jekyll-theme-hydeout


plugins:
  - jekyll-feed

paginate: 2

feed:
  path: atom.xml


